id: IC83C0B03
legacy_id: P000744
ocr_import_info:
  bdrc_scan_id: W1KG4779
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T10:21:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:48:26.494806+00:00'
last_modified: 2022-09-01 00:48:35.148249
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4779
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4779
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་རྟོགས་རྒྱན་གྱི་ཊི་ཀ
  author: ཅོ་ནེ་གྲགས་པ་བཤད་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8356689738444522
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1KG4837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4837
      total_pages: 244
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4837.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8356689738444522
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
