id: P000744
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:33.804121
source_metadata:
  id: bdr:W1KG4779
  title: མངོན་རྟོགས་རྒྱན་གྱི་ཊི་ཀ
  author: ''
  volumes:
    a303f16d134f44d080b863a56215f0d1:
      image_group_id: I1KG4837
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
